// backend/services/mockData.js

const MOCK_LIVE_MATCHES = [
  {
    id: "m1",
    leagueId: "pl",
    leagueName: "Premier League",
    status: "live",
    minute: 74,
    homeTeam: { id: "57", name: "Arsenal", logo: "🔴", score: 2, xG: 1.84 },
    awayTeam: { id: "65", name: "Man City", logo: "🩵", score: 1, xG: 1.12 },
    date: "Live",
    timestamp: new Date().toISOString(),
  },
];

const MOCK_UPCOMING_MATCHES = [
  {
    id: "m2",
    leagueId: "laliga",
    leagueName: "La Liga",
    status: "upcoming",
    date: "Today, 21:00",
    timestamp: new Date(Date.now() + 3600000 * 11).toISOString(),
    homeTeam: {
      id: "86",
      name: "Real Madrid",
      logo: "⚪",
      score: null,
      xG: null,
    },
    awayTeam: {
      id: "81",
      name: "Barcelona",
      logo: "🔵🔴",
      score: null,
      xG: null,
    },
    prediction: { homeWin: 42, draw: 28, awayWin: 30 },
  },
  {
    id: "m4",
    leagueId: "pl",
    leagueName: "Premier League",
    status: "upcoming",
    date: "Tomorrow, 15:00",
    timestamp: new Date(Date.now() + 3600000 * 29).toISOString(),
    homeTeam: {
      id: "64",
      name: "Liverpool",
      logo: "🔴",
      score: null,
      xG: null,
    },
    awayTeam: { id: "61", name: "Chelsea", logo: "🔵", score: null, xG: null },
    prediction: { homeWin: 55, draw: 25, awayWin: 20 },
  },
];

const MOCK_STANDINGS = [
  {
    id: "57",
    leagueId: "pl",
    name: "Arsenal",
    logo: "🔴",
    played: 28,
    won: 20,
    drawn: 5,
    lost: 3,
    gd: 38,
    points: 65,
  },
  {
    id: "65",
    leagueId: "pl",
    name: "Manchester City",
    logo: "🩵",
    played: 28,
    won: 19,
    drawn: 6,
    lost: 3,
    gd: 36,
    points: 63,
  },
  {
    id: "64",
    leagueId: "pl",
    name: "Liverpool",
    logo: "🔴",
    played: 28,
    won: 18,
    drawn: 7,
    lost: 3,
    gd: 32,
    points: 61,
  },
  {
    id: "61",
    leagueId: "pl",
    name: "Chelsea",
    logo: "🔵",
    played: 28,
    won: 15,
    drawn: 8,
    lost: 5,
    gd: 18,
    points: 53,
  },
];

const MOCK_SCORERS = [
  {
    id: "p1",
    name: "Erling Haaland",
    flag: "🇳🇴",
    teamName: "Manchester City",
    position: "Forward",
    stats: { goals: 28 },
  },
  {
    id: "p2",
    name: "Bukayo Saka",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    teamName: "Arsenal",
    position: "Forward",
    stats: { goals: 18 },
  },
  {
    id: "p3",
    name: "Mohamed Salah",
    flag: "🇪🇬",
    teamName: "Liverpool",
    position: "Forward",
    stats: { goals: 17 },
  },
];

const MOCK_MATCH_DETAILS = {
  m1: {
    id: "m1",
    leagueId: "pl",
    leagueName: "Premier League",
    status: "live",
    minute: 74,
    homeTeam: { id: "57", name: "Arsenal", logo: "🔴", score: 2, xG: 1.84 },
    awayTeam: {
      id: "65",
      name: "Man City",
      logo: "🩵",
      score: 1,
      xG: 1.12,
    },
    date: "Live",
    venue: "Emirates Stadium",
    referee: "Michael Oliver",
  },
  m2: {
    id: "m2",
    leagueId: "laliga",
    leagueName: "La Liga",
    status: "upcoming",
    date: "Today, 21:00",
    homeTeam: {
      id: "86",
      name: "Real Madrid",
      logo: "⚪",
      score: null,
      xG: null,
    },
    awayTeam: {
      id: "81",
      name: "Barcelona",
      logo: "🔵🔴",
      score: null,
      xG: null,
    },
    venue: "Santiago Bernabéu",
    referee: "Jesús Gil Manzano",
    prediction: { homeWin: 42, draw: 28, awayWin: 30 },
  },
  m4: {
    id: "m4",
    leagueId: "pl",
    leagueName: "Premier League",
    status: "upcoming",
    date: "Tomorrow, 15:00",
    homeTeam: {
      id: "64",
      name: "Liverpool",
      logo: "🔴",
      score: null,
      xG: null,
    },
    awayTeam: {
      id: "61",
      name: "Chelsea",
      logo: "🔵",
      score: null,
      xG: null,
    },
    venue: "Anfield",
    referee: "Anthony Taylor",
    prediction: { homeWin: 55, draw: 25, awayWin: 20 },
  },
};

module.exports = {
  MOCK_LIVE_MATCHES,
  MOCK_UPCOMING_MATCHES,
  MOCK_STANDINGS,
  MOCK_SCORERS,
  MOCK_MATCH_DETAILS,
};
