export const LEAGUE_FILTERS = [
  {
    code: "PL",
    name: "Premier League",
    logo: "https://crests.football-data.org/PL.png",
    country: "England",
    season: "2025/26",
    teamCount: 20,
  },
  {
    code: "PD",
    name: "La Liga",
    logo: "https://crests.football-data.org/laliga.png",
    country: "Spain",
    season: "2025/26",
    teamCount: 20,
  },
  {
    code: "BL1",
    name: "Bundesliga",
    logo: "https://crests.football-data.org/BL1.png",
    country: "Germany",
    season: "2025/26",
    teamCount: 20,
  },
  {
    code: "SA",
    name: "Serie A",
    logo: "https://crests.football-data.org/c111.png",
    country: "Italy",
    season: "2025/26",
    teamCount: 20,
  },
  {
    code: "FL1",
    name: "Ligue 1",
    logo: "https://crests.football-data.org/FL1.png",
    country: "France",
    season: "2025/26",
    teamCount: 20,
  },
  {
    code: "CL",
    name: "UEFA Champions League",
    logo: "https://crests.football-data.org/CL.png",
    country: "Europe",
    season: "2025/26",
    teamCount: 36,
  },
];
